version: '3'
services:
# use any name
  web:
    # using custom Dockerfile name
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app